# Generated by Django 5.0.6 on 2024-06-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='picture',
            field=models.ImageField(blank=True, default='room_fallback.jpg', upload_to='room/'),
        ),
    ]
