# Generated by Django 5.0.6 on 2024-06-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_roomtype_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='picture',
            field=models.ImageField(blank=True, default='room/room_fallback.jpg', upload_to='room/'),
        ),
    ]
