# Generated by Django 5.1.1 on 2024-09-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
