# Generated by Django 5.1.1 on 2024-09-21 02:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=43200)),
        ),
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(default=datetime.time(20, 0)),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
