# Generated by Django 5.1.1 on 2024-09-21 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='date_of_birth',
        ),
    ]
