# Generated by Django 5.1.1 on 2024-09-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_guest_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='date_of_birth',
            field=models.DateField(default='2002-01-01'),
        ),
    ]
