# Generated by Django 5.1.1 on 2024-11-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_tempguest'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='cottage_price',
            field=models.DecimalField(decimal_places=2, default=750, max_digits=10),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='is_cottage_required',
            field=models.BooleanField(default=True),
        ),
    ]
