# Generated by Django 5.1.1 on 2024-11-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_booking_adult_count_booking_is_overnight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempguest',
            name='user',
            field=models.IntegerField(),
        ),
    ]
