# Generated by Django 5.1.1 on 2024-11-08 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_alter_tempguest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempguest',
            name='adult_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tempguest',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 8, 0)),
        ),
        migrations.AddField(
            model_name='tempguest',
            name='check_out',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 8, 0)),
        ),
        migrations.AddField(
            model_name='tempguest',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=43200)),
        ),
        migrations.AddField(
            model_name='tempguest',
            name='is_overnight',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tempguest',
            name='kid_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tempguest',
            name='room',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tempguest',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
    ]
