# Generated by Django 5.1.1 on 2024-11-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_alter_guest_address_alter_guest_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
    ]
