# Generated by Django 5.1.1 on 2024-11-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_alter_guest_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
