# Generated by Django 5.1.1 on 2024-11-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_alter_guest_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('peak_months', models.JSONField()),
                ('off_peak_months', models.JSONField()),
            ],
        ),
    ]
