# Generated by Django 5.1.1 on 2024-11-12 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_remove_seasonaldata_year_seasonaldata_years'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomtype',
            old_name='price',
            new_name='based_price',
        ),
    ]
