# Generated by Django 5.1.1 on 2024-11-12 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_rename_price_roomtype_based_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomtype',
            old_name='based_price',
            new_name='price',
        ),
    ]
