# Generated by Django 5.1.1 on 2024-11-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_booking_booking_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullyBookedDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
    ]
