# Generated by Django 5.1.1 on 2024-11-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_fullybookeddates'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
