# Generated by Django 5.1.1 on 2025-01-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0031_booking_booking_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=25, unique=True)),
                ('value', models.TextField()),
            ],
        ),
    ]
