# Generated by Django 5.1.1 on 2025-01-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_manageemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('icon', models.ImageField(blank=True, default='amenities/amenities_fallback.jpg', upload_to='amenities/')),
            ],
        ),
    ]
